In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
df=pd.read_csv("Property_prices.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [41]:
medi=df.bedrooms.median()

In [43]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [45]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [47]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=2)

NameError: name 'X' is not defined

In [49]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression().fit(train_X, train_y)

NameError: name 'train_X' is not defined

In [51]:
reg.score(test_X, test_y)

NameError: name 'reg' is not defined

In [53]:
reg.score(train_X,train_y)

NameError: name 'reg' is not defined

reg.coef_

In [55]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(train_X, train_y)

NameError: name 'train_X' is not defined

In [57]:
lasso_reg.score(test_X, test_y)

NameError: name 'test_X' is not defined

In [59]:
lasso_reg.score(train_X, train_y)

NameError: name 'train_X' is not defined

In [61]:
from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(train_X, train_y)

NameError: name 'train_X' is not defined

In [63]:
ridge_reg.score(test_X, test_y)

NameError: name 'test_X' is not defined

In [65]:
ridge_reg.score(train_X, train_y)

NameError: name 'train_X' is not defined

In [67]:
reg.intercept_

NameError: name 'reg' is not defined

reg.predict([[3000,3,40]])

In [69]:
print(reg.predict([[3000, 3, 40]]))
print(reg.predict([[2500,4,5]]))

NameError: name 'reg' is not defined